language: scala
jdk: openjdk8
script: sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M "^^${SBT_VERSION}" scripted

matrix:
  include:
  - env: SBT_VERSION="0.13.18"
    scala: 2.10.7

  - env: SBT_VERSION="1.3.0"
    scala: 2.12.8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
